<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>oh yes!</title>
  </head>
  <body>
    <hr>
    <h1 align="center">CRIAR USUÁRIO</h1>
    <form align="center" action="/usuarios" method="post">
      <input type="email" name="email" placeholder="email">
      <input type="password" name="senha" placeholder="senha">
      <input type="submit" name="name" value="OK">
      <?= $data['csrf_inputs'] ?>
    </form>
    <hr>
    <h1 align="center">ALTERAR SENHA DE USUÁRIO</h1>
    <form align="center" action="/usuarios" method="post">
      <input type="email" name="email" placeholder="email">
      <input type="password" name="nova_senha" placeholder="senha">
      <input type="hidden" name="_METHOD" value="PUT"/>
      <input type="submit" name="name" value="OK">
      <?= $data['csrf_inputs'] ?>
    </form>
    <hr>
    <h1 align="center">DELETAR USUÁRIO</h1>
    <form align="center" action="/usuarios" method="post">
      <input type="email" name="email" placeholder="email">
      <input type="password" name="senha" placeholder="senha">
      <input type="hidden" name="_METHOD" value="DELETE"/>
      <input type="submit" name="name" value="OK">
      <?= $data['csrf_inputs'] ?>
    </form>
    <hr>
  </body>
</html>
