<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Slim3</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class=""><a href="dashboard">Dashboard </a></li>
                <li class="active"><a href="usuarios">Usuários </a></li>
                
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="login/exit">Sair</a></li>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <section class="container">
        <table class="table table-bordered">
            <tr class="active">
                <td><b>Email</b></td>
                <td><b>Alterar</b></td>
                <td><b>Remover</b></td>
            </tr>
            <?php foreach($data['usuarios'] as $usuario){ ?>

                <tr>
                    <td><?= $usuario['email'] ?></td>
                    <td><a href="alterar/<?= $usuario['id'] ?>">Alterar</a></td>
                    <td><a href="usuarios/excluir/<?= $usuario['id'] ?>">Excluir</a></td>
                </tr>

            <?php } ?>
        </table>
    </section>
</body>
</html>  
